package brag

import (
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/EmberGuild-Labs/tomfoolery/internal/config"
	"github.com/EmberGuild-Labs/tomfoolery/internal/state"
)

// RunningPID returns the pid of a live brag loop, or 0.
func RunningPID() int {
	pid, ok := state.ReadInt(state.PidFile())
	if !ok || pid <= 1 {
		return 0
	}
	if err := syscall.Kill(int(pid), 0); err != nil && err != syscall.EPERM {
		return 0
	}
	// Guard against pid reuse: the process must be us.
	out, _ := exec.Command("/bin/ps", "-o", "comm=", "-p", strconv.FormatInt(pid, 10)).Output()
	if !strings.Contains(string(out), "tomfoolery") && !strings.Contains(string(out), "uptime-brag") {
		return 0
	}
	return int(pid)
}

// Stop terminates a running brag loop. It reports whether one was running.
func Stop() bool {
	pid := RunningPID()
	if pid == 0 {
		state.Remove(state.PidFile())
		return false
	}
	syscall.Kill(pid, syscall.SIGTERM)
	for i := 0; i < 20 && RunningPID() != 0; i++ {
		time.Sleep(50 * time.Millisecond)
	}
	return true
}

// OpenWindow writes the .command file and asks the terminal app to open it.
// A .command file needs no Automation permission, unlike AppleScript.
func OpenWindow(bin string, cfg config.Config) error {
	script := fmt.Sprintf("#!/bin/zsh\n# Generated by tomfoolery. Runs the uptime-brag window.\nexec %s uptime-brag --loop\n",
		shellQuote(bin))
	if err := state.Write(state.CommandFile(), script, 0o755); err != nil {
		return err
	}
	app := "Terminal"
	if cfg.Brag.Terminal == "iTerm" {
		app = "iTerm"
	}
	args := []string{"-a", app, state.CommandFile()}
	if !cfg.Brag.Focus {
		args = append([]string{"-g"}, args...)
	}
	out, err := exec.Command("/usr/bin/open", args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("open %s: %v: %s", app, err, strings.TrimSpace(string(out)))
	}
	return nil
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Loop draws the brag window until the window closes or it is told to stop.
func Loop(cfg config.Config) error {
	boot, err := BootTime()
	if err != nil {
		return err
	}
	if pid := RunningPID(); pid != 0 && pid != os.Getpid() {
		fmt.Printf("\n  uptime-brag is already showing in another window (PID %d).\n", pid)
		return nil
	}
	if err := state.WriteInts(state.PidFile(), int64(os.Getpid())); err != nil {
		return err
	}
	cleanup := func() {
		if v, ok := state.ReadInt(state.PidFile()); ok && int(v) == os.Getpid() {
			state.Remove(state.PidFile())
		}
		fmt.Print("\033[?25h") // show cursor again
	}
	defer cleanup()

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGTERM, syscall.SIGHUP, syscall.SIGINT)

	now := time.Now()
	PrepareFuneral(boot, now)
	var fun *Funeral
	if f, ok := TakeFuneral(); ok {
		fun = &f
	}

	fmt.Print("\033]0;Uptime Brag\007\033[?25l")
	lastRows := 0
	lastSample := now
	sampleEvery := time.Duration(cfg.Brag.LastSeenIntervalMinutes) * time.Minute
	redraw := time.Duration(cfg.Brag.RedrawSeconds) * time.Second
	for {
		now = time.Now()
		if now.Sub(lastSample) >= sampleEvery {
			Sample(boot, now)
			lastSample = now
		}
		lines := Screen(now, boot, Record(), fun, cfg.Brag.MilestonesDays, cfg.Brag.WindowCols)
		rows := cfg.Brag.WindowRows
		if len(lines)+1 > rows {
			rows = len(lines) + 1
		}
		if rows != lastRows {
			// xterm window-resize sequence: CSI 8 ; rows ; cols t
			fmt.Printf("\033[8;%d;%dt", rows, cfg.Brag.WindowCols)
			lastRows = rows
		}
		fmt.Print("\033[H\033[2J" + strings.Join(lines, "\n"))

		// Sleep until the next redraw boundary so redraws land on the minute.
		next := now.Truncate(redraw).Add(redraw)
		select {
		case <-sigs:
			Sample(boot, time.Now())
			return nil
		case <-time.After(time.Until(next)):
		}
	}
}
