// Package shell renders the static hook file sourced from ~/.zshrc, and
// edits the marked block in rc files.
package shell

import (
	"fmt"
	"os"
	"strings"

	"github.com/EmberGuild-Labs/tomfoolery/internal/state"
)

const hookHeader = `# tomfoolery shell hook.
# Generated by ` + "`tomfoolery install`" + `; edits are overwritten on reinstall.
# Bypass any wrapper with: command ls, builtin kill, command pkill, command killall

# Interactive shells only. Scripts, cron jobs and subshells never see these.
case $- in *i*) ;; *) return 0 ;; esac

_tomfoolery_bin=%s
_tomfoolery_state="$HOME/.local/state/tomfoolery"

# ls: real ls first, then (sometimes) one line of gossip on stderr.
# "function ls" (not "ls()") so an existing ls alias cannot break the definition.
function ls {
  command ls "$@"
  local rc=$?
  if [ $rc -eq 0 ] && [ -t 1 ] && [ -t 2 ] && [ ! -f "$_tomfoolery_state/ls-gossip.off" ] && [ -x "$_tomfoolery_bin" ]; then
    local freq=35
    [ -r "$_tomfoolery_state/ls-gossip.freq" ] && freq=$(<"$_tomfoolery_state/ls-gossip.freq")
    case $freq in ''|*[!0-9]*) freq=35 ;; esac
    if [ $(( RANDOM %% 100 )) -lt "$freq" ]; then
      "$_tomfoolery_bin" ls-gossip --maybe -- "$@" >&2
    fi
  fi
  return $rc
}
`

// A wrapper for kill, pkill or killall. %[1]s is the command name, %[2]s is
// how to run the real one.
const killWrapper = `
# %[1]s: capture the victims, run the real %[1]s unchanged, then eulogize.
function %[1]s {
  if [ $# -eq 0 ] || [ ! -t 2 ] || [ -f "$_tomfoolery_state/kill-eulogy.off" ] || [ ! -x "$_tomfoolery_bin" ]; then
    %[2]s "$@"
    return
  fi
  local _tf_snap _tf_rc
  _tf_snap=$("$_tomfoolery_bin" kill-with-eulogy --capture %[1]s -- "$@" 2>/dev/null)
  %[2]s "$@"
  _tf_rc=$?
  if [ -n "$_tf_snap" ]; then
    if [ $_tf_rc -eq 0 ]; then
      "$_tomfoolery_bin" kill-with-eulogy --after "$_tf_snap" >&2
    else
      command rm -f -- "$_tf_snap"
    fi
  fi
  return $_tf_rc
}
`

// Inside a function, zsh prefixes a builtin's errors with the function name
// and line ("kill:7: kill 99 failed: ..."). Run builtin kill in the current
// shell (job specs need that) with stderr parked in a file, then restore the
// usual "kill: " prefix so the wrapper never changes kill's own messages.
const builtinKill = `
function _tomfoolery_builtin_kill {
  local _tf_err="$_tomfoolery_state/kill.err" _tf_rc
  if [ -d "$_tomfoolery_state" ] && [ -w "$_tomfoolery_state" ]; then
    builtin kill "$@" 2>"$_tf_err"
    _tf_rc=$?
    [ -s "$_tf_err" ] && command sed -E 's/^[^ ]*:[0-9]+: /kill: /' "$_tf_err" >&2
    return $_tf_rc
  fi
  builtin kill "$@"
}
`

// Render produces the hook file for the binary at bin, wrapping the given
// kill-family commands.
func Render(bin string, wrap []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, hookHeader, shellQuote(bin))
	for _, w := range wrap {
		switch w {
		case "kill":
			b.WriteString(builtinKill)
			fmt.Fprintf(&b, killWrapper, "kill", "_tomfoolery_builtin_kill")
		case "pkill", "killall":
			fmt.Fprintf(&b, killWrapper, w, "command "+w)
		}
	}
	return b.String()
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

const (
	blockStart = "# >>> tomfoolery >>>"
	blockEnd   = "# <<< tomfoolery <<<"
)

// RCBlock is the marked block appended to ~/.zshrc. It only sources a file,
// so nothing is spawned at shell startup.
func RCBlock() string {
	return blockStart + "\n" +
		"# Added by `tomfoolery install`. Remove with `tomfoolery uninstall`.\n" +
		`[ -f "$HOME/.config/tomfoolery/hook.zsh" ] && . "$HOME/.config/tomfoolery/hook.zsh"` + "\n" +
		blockEnd + "\n"
}

// HasBlock reports whether rc already contains the marked block.
func HasBlock(rcPath string) bool {
	b, err := os.ReadFile(rcPath)
	return err == nil && strings.Contains(string(b), blockStart)
}

// AddBlock appends the block to rcPath unless it is already there.
func AddBlock(rcPath string) (added bool, err error) {
	b, err := os.ReadFile(rcPath)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	text := string(b)
	if strings.Contains(text, blockStart) {
		return false, nil
	}
	if text != "" && !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	if text != "" {
		text += "\n"
	}
	mode := os.FileMode(0o644)
	if info, err := os.Stat(rcPath); err == nil {
		mode = info.Mode().Perm()
	}
	return true, state.Write(rcPath, text+RCBlock(), mode)
}

// RemoveBlock deletes the marked block (and one blank line before it).
func RemoveBlock(rcPath string) (removed bool, err error) {
	b, err := os.ReadFile(rcPath)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	text := string(b)
	start := strings.Index(text, blockStart)
	if start < 0 {
		return false, nil
	}
	end := strings.Index(text[start:], blockEnd)
	if end < 0 {
		return false, fmt.Errorf("%s: found %q without a matching end marker; edit it by hand", rcPath, blockStart)
	}
	end += start + len(blockEnd)
	if end < len(text) && text[end] == '\n' {
		end++
	}
	if start >= 2 && text[start-2:start] == "\n\n" {
		start--
	}
	info, _ := os.Stat(rcPath)
	return true, state.Write(rcPath, text[:start]+text[end:], info.Mode().Perm())
}
